% coding:utf-8

% Ausführen in R: 
% Sweave("C:/Daten/Daniel/studium/git_repo/sem2/stoc/sw06/sw06_3.Rnw",encoding='UTF-8')

\section{Aufgabe 3}

\subsection{a}
$\dfrac{x}{n} \pm \dfrac{1.96}{\sqrt{n}} 
\cdot \sqrt{\dfrac{x}{n} \left(1 - \dfrac{x}{n}\right)}$\\
$= \dfrac{7}{50} \pm \dfrac{1.96}{\sqrt{50}} 
\cdot \sqrt{\dfrac{7}{50} \left(1 - \dfrac{7}{50}\right)}$\\
$ = [0.0438, 0.2362]$

\subsection{b}
<<>>=
binom.test(x=7,n=50,p=0.5,conf.level=0.95)
@
