% coding:utf-8

% Ausführen in R: 
% Sweave("C:/Daten/Daniel/studium/git_repo/sem2/stoc/sw10/sw10_2.Rnw",encoding='UTF-8')

\section{Aufgabe 2}

\subsection{a}
Es handelt sich um ungepaarte Stichproben. 

\subsection{b}

\subsection{c}
<<>>=
# jackals=read.table("http://stat.ethz.ch/Teaching/Datasets/jackals.dat", header=TRUE)
jackals=read.table("jackals.dat", header=TRUE)
t.test(jackals[,'M'], jackals[,'W'], var.equal = TRUE)
@

\subsection{d}
<<>>=
wilcox.test(jackals[,'M'], jackals[,'W'], var.equal = TRUE)
@

\subsection{e}
<<fig=TRUE>>=
qqnorm(jackals[,"M"])
qqline(jackals[,"M"],col='green')
@
<<fig=TRUE>>=
qqnorm(jackals[,"W"])
qqline(jackals[,"W"],col='green')
@ \\
Aufgrund der qqplots kann von einer Normalverteilung ausgegangen werden. 
Daher ist der t-Test präziser. \\
Der Wilcoxon-Test wäre besser geeignet, wenn die Daten nicht normal verteilt 
wären. 
