% coding:utf-8

% Ausführen in R: 
% Sweave("C:/Daten/Daniel/studium/git_repo/sem2/stoc/sw09/sw09_4.Rnw",encoding='UTF-8')

\section{Aufgabe 4}

\subsection{a}
<<>>=
x=c(71,69,67,68,73,72,71,71,68,72,69,72)
Z=sqrt(length(x))*(mean(x)-70)/1.5
Z
@
\[ K= (-\infty, -1.5 \]
Z liegt nicht im Verwerfungsbereich

\subsection{b}
<<>>=
T=sqrt(length(x))*(mean(x)-70)/sd(x)
T
@
\[ K= (-\infty, -1.782 \]
T liegt nicht im Verwerfungsbereich